- hosts: localhost
  become: true
  user: root
  tasks:
  - name: Pull image
      docker_image:
        name: shivanshsethi2000/mern-social:latest
        source: pull
  - name: removing previous minikube containers
    command: sudo minikube delete
  - name: Starting minikube
    command: sudo minikube start --cpus 4 --memory 8192 --force
  - name: Deploy the application
    command: sudo kubectl apply -f deployment.yml
  - name: Deploy the service
    command: sudo kubectl apply -f service.yml
  - name: Waiting for pod to run
    ansible.builtin.pause:
      minutes: 2
  - name: Wesite Deploying on localhost:80
    command: sudo kubectl port-forward service/mern-social 80