apiVersion: v1
kind: Service
metadata:
  name: mern-social
spec:
  selector:
    app: mern-social
  ports:
    - name: http
      protocol: TCP
      port: 3000
      targetPort: 3000
  type: LoadBalancer